### ISSUE TITLE
[Enhancement] Flag in a Card

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1063]
**Is your enhancement request related to a problem? Please describe.**
We would like to have a "flag" flavor of our card, which has a "flag" in the very top/header of the card

![Skærmbillede 2020-06-09 kl  11 01 41](https://user-images.githubusercontent.com/49033002/84132142-cb63c480-aa45-11ea-870a-87f2bbc02774.png)

https://zpl.io/ag4NLYZ

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or enhancement you've considered.

**Additional context**

**Comment by jkaltoft** [comment]
@jakobe , @henrikvoetmand  and I had a chat regarding this issue.

Summary:

- Reuse existing `kirby-card-header` component instead of creating a new component.
- Extend `kirby-card-header` with a property to "flag" the header.
    - Name the property `flagged`
        - Among other names considered were `attention-level` but since "flag" is already a concept used for this type of "thing" I've decided on using `flagged` to keep a familiar terminology.
    - Options correspond to the `themeColor` property options in the `kirby-flag` component.
- Currently it is technically possible to use multiple `kirby-card-header`s inside `kirby-card`. As I understand it the flagged variant is not supposed to be applied in combination with a regular `kirby-card-header`, so no modifications will be done to address this.

**Comment by jkaltoft** [comment]
>   * Options correspond to the `themeColor` property options in the `kirby-flag` component.

@henrikvoetmand @jakobe Maybe this should be reconsidered. I think it makes less sense to flag a card using the terms `semi-light` and `transparent`.

- Would `informational` or `neutral` be better words for `semi-light`?
- Any suggestions for another word than `transparent`? Or should I just stick to that?

**Comment by bommariusser** [comment]
nicely done writing all this down @jkaltoft :) 

we had the same discussion back when we did the flag, concerning the naming. I think naming should follow along. If we think neutral/informational is better then semi-light then both should be changed :) 

in regards to the transparent flag, we dont have any usecase for this being in a card, neither do we have a "semi-light" version iirc, although i think this is relevant to have :) 

i love the fact that you are taking card header in consideration, totally the right thing to do. Card header/footer might also be something we should refactor. The exisiting header/footer is not used right now, but it should. I made task for refactoring the header/footer to something more relevant,  that is actually "alive" in our Kirby sketch library :) 

Sizing is available in our normal flags but it shouldnt be in card flags. Probably something you have talked about, but i just want to be sure :)

**Comment by jkaltoft** [comment]
> we had the same discussion back when we did the flag, concerning the naming. I think naming should follow along. If we think neutral/informational is better then semi-light then both should be changed :)

I chatted with @henrikvoetmand and we agreed on `informational` - which is also the naming in [Zeplin](https://app.zeplin.io/project/5e1f27f01ffb15bd95efc426/styleguide/components?coid=5ea978087df87926143c4056) so that makes most sense.

I think changing the naming in the Flag component is out of scope for this issue, but I certainly agree that it should follow along. I'll try to remember to create an issue for it.
