### ISSUE TITLE
[Enhancement] Segmented Chip Control with lower attention (Periodevælger)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1126]
**Is your enhancement request related to a problem? Please describe.**
We want to give the user an easy way to change between periods on the price graph. Right now the user changes periods with a dropdown, which takes many clicks. Instead we want to implement a Segmented Chip Control. 
The user needs to be able to change between 7-8 periods and we want them all to be visible to the user so he easily can change between them. If we implement the Segmented Chip Control as it is the user can only see 4-5 chips at a time, so we need to create a compressed version of the component. 

**Describe the solution you'd like**
In order to have 7-8 chips on the screen at the same time we propose that we are able to make the following adjustments to the Segmented Chip Control: 
- Set the minimum chip width to 44px
- Set the spacing between chips to 4px (0px for iPhone SE)
- Set the unselected chip color to Transparent

Note: We have to find a way where we don't break existing features - Searching a paper uses the segmented chip control right now.

Challenge: The segmented chip control will bypass the page margin on small devices (the 8px). So how can by scroll vertically out of the screen to see the remaining chips?

**Describe alternatives you've considered**
NA

**Additional context**

iPhone 8
![Skærmbillede 2020-09-01 kl  12 03 27](https://user-images.githubusercontent.com/53176253/91841545-dbf59680-ec52-11ea-815c-85b6022ddc8c.png)

iPhone SE
![Skærmbillede 2020-09-01 kl  12 03 32](https://user-images.githubusercontent.com/53176253/91841559-df891d80-ec52-11ea-9fd6-f3b45a5c514b.png)

**Comment by LVinther** [comment]
Efter møde med Alexander og Marvin blev det besluttet, at der skal udstilles en række variable (afstand mellem knapper, padding indeni knapper og transparens) samtidig med, at man skal kunne skalere komponenten, så den optimeres til små skærme (iPhone SE). Da disse muligheder kun skal bruges til én ting i team 3 lige pt. skal det kun være en one-off mulighed for nu.

**Comment by jakobe** [comment]
@LVinther Is this still relevant? 🤔

**Comment by LVinther** [comment]
@jakobe Yes, this is still highly relevant :)

**Comment by RasmusKjeldgaard** [comment]
**Tech refinement:** this seems like a very specific requirement, that will work for 7-8 chips, but no more than that. What if projects have use cases for 20 chips? 

A suggestion could be to preserve the horizontal scrolling that is already present when there are too many chips, but make it more clear that you can scroll/ that there are more chips outside the screen.

Or, it could be that we simply make it a UX guideline to use a dropdown when there are more options to choose from than segmented chip control can support.

**Comment by RasmusKjeldgaard** [comment]
**Tech refinement 2:** As for the lower attention level, we suggest to expose the background color like `--kirby-item-background` on [item](https://cookbook.kirby.design/home/showcase/item)

**Comment by bommariusser** [comment]
we have a guideline for that but the usecase is still valid - Right now this is a one-off so keep it simple i think so it sounds like a valid resolution @RasmusKjeldgaard what do u say @henrikvoetmand

**Comment by MadsBuchmann** [comment]
**Final Refinement )** 

The [segmented control](https://cookbook.kirby.design/home/showcase/segmented-control) in chip mode should be expanded such that it is possible to set `size = 'sm'`. 

When `size = 'sm'` the following should happen: 
* minimum width of the chips shall be 44px
* spacing between the chips shall be 4px or... 
* ... if the screen width is <= 320 pixels (iPhone SE) - the spacing should be 0px. 

`size` should `'md'` by default to not break anything. 

This will make it possible to have 7 - 8 chips on the screen at a time when `size = 'sm'` and the text in the chips is no more than ~2 characters long. After talking with @henrikvoetmand a guideline should be created that suggests that UXers use a [dropdown](https://cookbook.kirby.design/home/showcase/dropdown) instead of a segmented control. 

In regards to the transparent background - expose the background color as @RasmusKjeldgaard suggests: https://github.com/kirbydesign/designsystem/issues/1126#issuecomment-829037488

**Comment by MadsBuchmann** [comment]
Should be ready for both UX- and code review now 🔎

It can be seen in action here: [INSERT LINK]

Here's a couple of screenshots to show how it acts when the content is only ~2 characters 😄

### Width larger than 320 px & transparent background
![Screenshot 2021-05-18 at 15 57 03](https://user-images.githubusercontent.com/17269698/118665078-4d31a580-b7f2-11eb-842c-8e2208b8a17a.png)

### Width is 320 px & transparent background
![Screenshot 2021-05-18 at 15 56 53](https://user-images.githubusercontent.com/17269698/118665234-70f4eb80-b7f2-11eb-8a81-3b80181b8e1e.png)

### Width larger than 320 px & white background 
![Screenshot 2021-05-18 at 15 56 07](https://user-images.githubusercontent.com/17269698/118665313-7fdb9e00-b7f2-11eb-8f1d-56f67ec5bf13.png)

### Width is 320 px & white background 
![Screenshot 2021-05-18 at 15 55 55](https://user-images.githubusercontent.com/17269698/118665361-89fd9c80-b7f2-11eb-8fd8-a17b6413011b.png)

**Comment by MadsBuchmann** [comment]
After review it has been decided to change gears a bit. 

Instead of implementing the suggested changes via `themeColor` & `size` an additional mode will be created such that the `mode` input property now can take on the following 3 values: `default`, `chip` & `compactChip`. 

When the mode is `compactChip` it will change to transparent background, set the desired spacing & shrink on iPhone SE.
