### ISSUE TITLE
[Enhancement] Cards shouldn't have 8px padding on small screens

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1199]
**Is your enhancement request related to a problem? Please describe.**
It is an improperly behavior that the card adapts to small screens, there must be space in the card so it fulfills the design principle 'Invisible design' and it should only be a page or modal that must control the padding.

see also this behavior. 
<img width="646" alt="Skærmbillede 2020-11-18 kl  12 38 06" src="https://user-images.githubusercontent.com/49033002/99525997-e9d9ce80-299a-11eb-95a6-46f98a570b96.png">

**Describe the solution you'd like**
We **don't** want the Card component to be the only component that handles small screens - thus we want to remove this behavior on the Card so it should always be 16. It should only be the page/modal where the components are living in that should handle such a thing. 

![Skærmbillede 2020-11-16 kl  12 54 24](https://user-images.githubusercontent.com/49033002/99249952-368e9f80-280b-11eb-8457-907885579401.png)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or enhancement you've considered.

**Additional context**
We should think about a **layout component** that takes care of the padding, instead of inserting it manually in our views.

**Comment by LinePatricia** [comment]
![Uploading image (2).png…]()

**Comment by LinePatricia** [comment]
![image (2)](https://user-images.githubusercontent.com/61691221/99257084-b837fa80-2816-11eb-9b26-0deb4e45761a.png)
![image (1)](https://user-images.githubusercontent.com/61691221/99257099-bf5f0880-2816-11eb-8c15-37d469c48e2b.png)

**Comment by LinePatricia** [comment]
**Is your enhancement request related to a problem? Please describe.**
It is an improperly behavior that the card adapts to small screens, there must be space in the card so it fulfills the design principle 'Invisible design' and it should only be a page or modal that must control the padding.

**Describe the solution you'd like**
We don't want the Card component to be the only component that handles small screens - thus we want to remove this behavior on the Card so it should always be 16. It should only be the page/modal where the components are living in that should handle such a thing.

**Describe alternatives you've considered**
No alternatives for now

**Additional context**
We should think about a layout component that takes care of the padding, instead of inserting it manually in our views.
