### ISSUE TITLE
[Enhancement] Button rules in MessagingStates / EmptyStates

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1222]
**Is your enhancement request related to a problem? Please describe.**
At this moment of time the component all combinations of buttons and placements of buttons, like 2 attentionlvl 1 buttons placed as number 2 and 3. This ends up in 

**Describe the solution you'd like**
We would like to have clearly defined rules of what is allowed in a MessagingState / Emptystate:

1. If you have a button that is attentionlvl1, this can only be placed at the first place - and there can only be one!
2. All the other buttons should be attentionlvl3 and the first button can also be attentionlvl3

**Describe alternatives you've considered**
Nothing

**Additional context**
If people have implemented another button like attentionlvl2 or 4 it should default to a attentionlvl3.
![Button rules](https://user-images.githubusercontent.com/49033002/101319593-87ba0e00-3862-11eb-9d45-1b82192324c0.png)

**Comment by hafstad** [comment]
Empty State component changes the attentionlevel of the buttons to `attention-level=3` except the first of type if `attention-level=1` 

`@ContentChildren(ButtonComponent): QueryList<ButtonComponent>` to query the buttons, needs to be done inside ngAfterContentInit because they are projected inside empty state. Also subscribe to changes on the query list.
