### ISSUE TITLE
[BUG] Can't use Kirby module in unit test - Injected window is not resolved

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1624]
**Describe the bug**
In Drb integration tests, we want to interact with the real kirby module in integration tests but we get the error:

"Can't resolve all parameters for ModalHelper: ([object Object], [object Object], ?)", referring to Window not being resolved.

The window should have been provided automatically by importing the kirby module, [as window is provided in KirbyModule](https://github.com/kirbydesign/designsystem/blob/734aaed233d08dd102efdbafddc887846af70214/libs/designsystem/src/lib/kirby.module.ts#178).

I have even tried also providing the kirby windowRef in the Jest tests DI setup, with no luck.

A demo of the problem is on the Drb branch: rma/kirby-integrationtest-windowdi-demo

**To Reproduce**

Run an integration test and remove the overrideModule statement, overriding KirbyModule with KirbyTestingModule in the integrationTestingFactory.

**Kirby version**
- 2.0.7

**Expected behavior**

It should at least be possible to provide the kirby window so you can run the real KirbyModule in Jest integration tests.

**Screenshots**

<img width="1016" alt="Screen Shot 2021-06-15 at 10 24 29" src="https://user-images.githubusercontent.com/9210691/122019919-93affb00-cdc4-11eb-9d84-91cf6939aaa3.png">

**Please complete the following information:**
- OS: Mac
- Browser Chrome

**Additional context**

## Tasks:
- [ ] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by andershessellund** [comment]
I looked a little into this issue, and it is a *compile* time error, that is, it happens when angular attempts to compile any class that uses ModalHelper in their constructor (or depends recursively on one that does).

In some cases, the error produces a better error message:

"This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
  This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.
  Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors."

WindowRef does not have any decorators, and it extends Window which also does not have any decorators.

The solution is to use an InjectionToken to inject window instead.

**Comment by mvindahl** [comment]
I played with it too. Tried defining an InjectionToken and injecting by that but to no avail. A solution that *did* work was to create a class wrapper around the window instance and to annotate it as injectable in root scope. I've tested this with the DRB tests and I've verified that this makes it possible for them to use KirbyModule. PR incoming.
