### ISSUE TITLE
[RESEARCH] Enable full window scrolling for virtual scroll on kirby page

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1819]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
We need to find out a way to enable full window scrolling together with our page, in a virtual scroll context, based on our initial findings, listed below:

So far, we have seen the best results using [Angular's virtual scrolling CDK](https://material.angular.io/cdk/scrolling/overview), at least for more simple use-cases. It seems to work well with web-components, and needs no tweaks or extra settings to work out of the box. Ionic also uses this as the starting point in their [virtual scroll guide](https://ionicframework.com/docs/angular/virtual-scroll).

The virtual scroll list will in most cases be embedded in a `kirby-page`, with a page header and other elements. In these use cases, it is the responsibility of the page to handle scrolling, so we need to figure out how scrolling a page will virtualise the list items that are placed inside the list, within the page, when scrolling happens on the page itself.

I have created a series of commits, where V3 showcases how that would likely look: https://github.com/kirbydesign/designsystem/compare/test/cdk-virtual-scroll-on-page 
Here, the virtual scroll viewport element wraps the entire page, and becomes the scrolling root. That issue here is that while the items we want to render are actually added to the DOM, they are not visible. 

This can be verified by inspecting down to the kirby-list-experimental level in the inspector, and when scrolling the seemingly empty viewport in the example far enough, the items seem to be correctly virtualised even though they are never correctly shown. 
So this could be a starting-point for investigating the interplay between `kirby-page` and the `cdk-virtual-scroll-viewport` element.

V1 and V2 each show a simpler working example with ion-content and kirby-page-content respectivly, e.g. without kirby-page involved. It is not what we want in the end, but shows that what we want seems possible. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by RasmusKjeldgaard** [comment]
This needs further clarification and breakdown into smaller issues. Could be a can of worms, so we need to do our research.

**Comment by RasmusKjeldgaard** [comment]
I have edited the original issue so it now better represents the research that should be done.

**Comment by RasmusKjeldgaard** [comment]
Quick thought: 
The area that should is currently scrollable in the page is the <main> element inside ion-content, so I think a good investigation would be to try change/simplify the page so we could project something like the below snippet directly into the ion-content block, and see how that works:

```
<cdk-virtual-scroll-viewport itemSize="56" minBufferPx="900" maxBufferPx="1350">
      <kirby-list-experimental>
        <kirby-item *cdkVirtualFor="let item of itemsFullList">
          <h3>{{item.title }}</h3>
        </kirby-item>
      </kirby-list-experimental>
</cdk-virtual-scroll-viewport>
```

**Comment by MadsBuchmann** [comment]
"Timebox": We will be working on this Friday the 14 of January and then we will have a chat with @RasmusKjeldgaard on Monday the 17th of January regarding our findings.

**Comment by MadsBuchmann** [comment]
The allocated time has been spent - we've decided to keep this issue open and define a desired outcome. 

A small writeup of what we've figured out so far! 

I've found a custom strategy from [a issue comment in the angular/components repository](https://github.com/angular/components/issues/13862#issuecomment-889848447): https://stackblitz.com/edit/window-virtual-scroll-strategy 

The above custom strategy makes it possible to have the `cdk-virtual-scroll-viewport` only wrapping the `kirby-list-experimental` element while using the `body` elements scrollbar to scroll the list instead of the one applied by the viewport element. 

However when a `kirby-list-experimental` element is nested as below the body element does not have any scrollbar: 
```html
kirby-page
   kirby-page-content
      cdk-virtual-scroll-viewport
          kirby-list-experimental
```

Instead the scrollbar that can be seen is owned by a `main` element that is a child of the `ion-content` element that is part of the `kirby-page` template. 

Hence i had to modify the strategy to listen for the `ionScroll` event instead of the `scroll` event on window as well as changing which element it should use as viewport. 

The following commit contains references to all the relevant files of the POC: https://github.com/kirbydesign/designsystem/commit/60726cbeeb8ace6f4882d4d2b6961b4b3ea58bc4 

The following scss file is also important to get it to work: [app.component.scss](https://github.com/kirbydesign/designsystem/commit/43a14bcfc0c8bd80b7969e90edbdf012472dc3c9#diff-c42345dc9d5ae4137ab68cefb63e1ba6f43c1070560053f7376ac8c11cf6466f)

What is left to do is figuring out how to:   
- [ ] Gain a better understanding of the modified strategy & refactor it
- [ ] Confirm it works with the kirby-router
- [ ] Confirm it works with load on demand functionality 
- [ ] Try to merge it with a autosizing strategy (paging @RasmusKjeldgaard for more details)

The desired outcome is to create a codesnippet that can be sent to DRB.

**Comment by MadsBuchmann** [comment]
# Write-up 
To conclude the reasearch done for this issue; here's a write-up! 

## How do i make a list with full window scrolling? 

To do this we need to: 
1. Construct the markup such that it can be used with virtual scroll
2. Define a custom virtual scroll strategy that allows us to replace the cdk-virtual-scroll `scroll` event as the one triggering rerendeirng of the virtual list
3. Define & use a directive for applying the custom virtual scroll strategy 
4. Optional: tag on "load on demand" functionality

## 1. Construct the markup such that it can be used with virtual scroll
The markup looks as follows: 
```html
// app.component.html
<kirby-page title="Virtual Scroll Test">
  <kirby-page-content>
    <h1>This is an example of content in page</h1>
    <p>
      The minBufferPx and maxBufferPx controls how much content is buffered. Increasing it will 
      make the scrolling more smooth but requires more resources; decreasing requires less resources but makes it more jaggy. 
    </p>
    <cdk-virtual-scroll-viewport
      kirbyPageVirtualScrollStrategy
      [minBufferPx]="1080 * 0.5"
      [maxBufferPx]="1080 * 1"
    >
      <section>
        <div *cdkVirtualFor="let item of items; let idx = index">
          <kirby-section-header style="height: 56px; display: block;" *ngIf="item.type === 'header'"
            ><h2>{{ item.content }}</h2></kirby-section-header
          >
          <kirby-item
            *ngIf="item.type === 'item'"
            [class.first-item]="items[idx - 1]?.type === 'header'"
            [class.last-item]="items[idx + 1]?.type === 'header'"
            class="shadow"
          >
            {{ item.content }}
          </kirby-item>
        </div>
      </section>
    </cdk-virtual-scroll-viewport>
  </kirby-page-content>
</kirby-page>
```

Notice that we're not using `kirby-list-experimental` & that the structure inside the `div` that the directive `cdkVirtualFor` has been applied to is flat: 

- Not using `kirby-list-experimental` is necessary as we need more control of the structure in order to apply the `cdkVirtualFor` directive. Furthermore the 
selectors used for applying styling to the items in `kirby-list-experimental` does not function when using virtual scrolling as it alters the DOM structure. 
- Keeping the structure inside the element that has `cdkVirtualFor` applied flat is necessary as the children of this element are virtualized. If we had elements nested in other elements, for example a section of items, the section would be virtualized and not the individual items. 

As the list styling is not applied by `kirby-list-experimental` we have to manually apply the styling to the items. This is done by the `first-item`, `last-item` and `shadow` classes. 

_Side note:_  the `cdkVirtualFor` directive is applied to a `div` element. It is possible to use a `ng-container` instead; it will however affect performance negatively. I think this is because  a lot of javascript is executed each time a `ng-container`  element is rendered.

## 2. Define a custom virtual scroll strategy that allows us to replace the cdk-virtual-scroll `scroll` event as the one triggering rerendeirng of the virtual list
The `angular/cdk` exposes a `VirtualScrollStrategy` interface that can be used to define custom scrolling strategies. 
By default the `FixedSizeVirtualScrollStrategy` strategy is used which requires all elements to have the same height. For this example we extend that strategy in order to: 
- Redefine when `onContentScrolled` is triggered. This function is responsible for rendering new elements in the viewport and is by default triggered every time the `cdk-virtual-scroll-viewport` is scrolled.
- Overwrite the `getViewportSize` method of the viewport. This function returns the height of the viewport. Normally it would be the height of `cdk-virtual-scroll-viewport` but we can overwrite it to pass the height of for example the `window` element instead. 
- Overwrite the `measureScrollOffset` method of the viewport. As with getViewportSize the default functions reads the scroll offset from `cdk-virtual-scroll-viewport`. But we can't use that in this context. 

```typescript 
// strategy.ts 
/* eslint-disable no-underscore-dangle */
import { CdkVirtualScrollViewport, FixedSizeVirtualScrollStrategy } from '@angular/cdk/scrolling';
import { Observable, Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

export class GenericEventVirtualScrollStrategy extends FixedSizeVirtualScrollStrategy {
  private readonly destroy = new Subject<void>();
  private destroy$: Observable<void>;

  constructor(
    itemSizePx: number,
    minBufferPx: number,
    maxBufferPx: number,
    private observable$: Observable<any>,
    private getViewportSize: () => number,
    private measureScrollOffset: () => number
  ) {
    super(itemSizePx, minBufferPx, maxBufferPx);
    this.destroy$ = this.destroy.asObservable();
  }

  attach(viewport: CdkVirtualScrollViewport) {
    viewport.getViewportSize = this.getViewportSize;
    viewport.measureScrollOffset = this.measureScrollOffset;

    super.attach(viewport);

    this.observable$.pipe(takeUntil(this.destroy$)).subscribe(() => {
      super.onContentScrolled();
    });
  }

  detach() {
    super.detach();
    this.destroy.next();
    this.destroy.complete();
  }

  updateItemAndBufferSize(itemSize: number, minBufferPx: number, maxBufferPx: number) {
    super.updateItemAndBufferSize(itemSize, minBufferPx, maxBufferPx);
  }
}
```

Notice that the strategy accepts any observable for triggering `super.onContentScrolled()` - which means it is not limited to be activated on scroll events. 
The two methods `getViewportSize` and `measureScrollOffset` is also not specified but given as part of the constructor. For easy experimentation i decided on providing 
these in the directive using the strategy. But it is of course possible to just provide them directly in this strategy.

side note: there exists an experimental [AutoSizeVirtualScrollStrategy](https://github.com/angular/components/blob/master/src/cdk-experimental/scrolling/auto-size-virtual-scroll.ts) in `@angular/cdk-experimental`. The `GenericEventVirtualScrollStrategy` can extend that one to allow for various sizes in the virtualization. However it is experimental and was a bit janky. But perhaps worth playing around with a bit more.  

## 3. Define & use a directive for applying the custom virtual scroll strategy 
We now need a directive that we can use to apply the `GenericEventVirtualScrollStrategy` strategy. 

The below directive: 
- creates input properties such that data that is needed for the `GenericEventVirtualScrollStrategy` constructor can be passed. 
- defines the `getViewportSize` & `measureScrollOffset` functions. They could use some more work but work for now. See the todo comments. 
- defines an observable that the `GenericEventVirtualScrollStrategy` can use to trigger `onContentScrolled`. 

```typescript
// strategy.directive.ts
/* eslint-disable no-underscore-dangle */
import { coerceNumberProperty } from '@angular/cdk/coercion';
import { VIRTUAL_SCROLL_STRATEGY } from '@angular/cdk/scrolling';
import { Directive, forwardRef, Input, OnChanges, OnInit } from '@angular/core';
import { fromEvent } from 'rxjs';

import { GenericEventVirtualScrollStrategy } from './strategy';

const factory = (dir: KirbyPageVirtualScrollDirective) => dir._scrollStrategy;

@Directive({
  selector: 'cdk-virtual-scroll-viewport[kirbyPageVirtualScrollStrategy]',
  providers: [
    {
      provide: VIRTUAL_SCROLL_STRATEGY,
      useFactory: factory,
      deps: [forwardRef(() => KirbyPageVirtualScrollDirective)],
    },
  ],
})
export class KirbyPageVirtualScrollDirective implements OnChanges, OnInit {
  observable$ = fromEvent(window, 'ionScroll');
  event: any;

  ngOnInit() {
    this.observable$.subscribe((value) => {
      this.event = value;
    });
  }

  /** The size of the items in the list (in pixels). */
  @Input()
  get itemSizePx(): number {
    return this._itemSizePx;
  }
  set itemSizePx(value: number) {
    this._itemSizePx = coerceNumberProperty(value);
  }
  _itemSizePx = 56;

  /**
   * The minimum amount of buffer rendered beyond the viewport (in pixels).
   * If the amount of buffer dips below this number, more items will be rendered. Defaults to 100px.
   */
  @Input()
  get minBufferPx(): number {
    return this._minBufferPx;
  }
  set minBufferPx(value: number) {
    this._minBufferPx = coerceNumberProperty(value);
  }
  _minBufferPx = 100;

  /**
   * The number of pixels worth of buffer to render for when rendering new items. Defaults to 200px.
   */
  @Input()
  get maxBufferPx(): number {
    return this._maxBufferPx;
  }
  set maxBufferPx(value: number) {
    this._maxBufferPx = coerceNumberProperty(value);
  }
  _maxBufferPx = 200;

  /** The scroll strategy used by this directive. */
  _scrollStrategy = new GenericEventVirtualScrollStrategy(
    this.itemSizePx,
    this.minBufferPx,
    this.maxBufferPx,
    this.observable$,
    () => window.innerHeight, // TODO: provide a better function for `getViewportSize`. It should be based on kirby-page not window. 
    () => (this.event ? this.event.detail.scrollTop : window.pageYOffset) // TODO: provide a better function for measureScrollOffset. It should be based on kirby-page not window.
  );

  ngOnChanges() {
    this._scrollStrategy.updateItemAndBufferSize(
      this.itemSizePx,
      this.minBufferPx,
      this.maxBufferPx
    );
  }
}
```

Notice that `observable$ = fromEvent(window, 'ionScroll');` uses `ionScroll` and not just `scroll`. This is because `ionScroll` is emitted from `kirby-page` as it uses ionic below the surface. This makes it possible to react to scrolls on the page. 

Side note: This directive could use some more work - i think there might be gains in terms of reducing jankiness by resolving the two TODOS. 

## 4. Optional: tag on "load on demand" functionality

The `kirby-list` component provides a `loadOnDemand` event emitter that can be used to load in new data, when a certain threshold has been reached. 
To recreate this functionality we can simply attach an event listener that triggers on `ionScroll`:
```typescript
// app.component.ts
import { AfterViewInit, Component, HostListener } from '@angular/core';

@Component({
  selector: 'cookbook-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements AfterViewInit {
  items: any;
  maxScrollBarLength: number;
  itemHeightPx = 56; 
  title = 'Kirby design system';

  constructor() {
    this.items = this.generateItems(500);
  }

  ngAfterViewInit() {
    this.maxScrollBarLength = this.items.length * 56;
    this.listenForLoadOnDemand();
  }

  listenForLoadOnDemand() {
    window.addEventListener('ionScroll', (event: any) => {
      if (event.detail.scrollTop / this.maxScrollBarLength > 0.75) {
        console.log('loading!');
        this.items = this.generateItems(this.items.length + 500);
        this.maxScrollBarLength = this.items.length * this.itemHeightPx;
      }
    });
  }

  generateItems(n: number) {
    return [...Array(n).keys()].map((idx) =>
      idx % 10 === 0
        ? {
            type: 'header',
            content: `Section Header ${idx / 10}`,
          }
        : {
            type: 'item',
            content: `Item ${idx % 10}`,
          }
    );
  }

  
}
```
