### ISSUE TITLE
[Housekeeping] Clean up NX configurations to register multiple packages

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1976]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request
To build our monorepo structure we're utilizing [NX](https://nx.dev/). However the `Core` library is not registered as a project in NX the same way `designsystem` is. As can be seen in the file `angular.json` & `nx.json`. 

First off registering core as a project in NX, will allow for lower build times due to caching of earlier runs. But furthermore i think it is worth investigating what we could gain from it and to be consistent in the way we setup projects with our build tool.

**Comment by RasmusKjeldgaard** [comment]
I have been looking into simplifying our NX setup a bit, and structure it more like separate packages, so we are a bit more decoupled from Angular.

In combination with NX, [Lerna](https://lerna.js.org/) seems to be a quite powerful tool to get all the combined goodies of: cached processes, bootstrapping/symlinking the projects together while developing, and managing the publishing of several packages either independently of each other or with shared version numbers/increments. 

I tried using Lerna in a fresh workspace with only our Angular components and a simple app, but unfortunately I can't quite get the lerna bootstrapping to work. We use ng-packagr to create a distribution bundle, and because ng-packagr takes care of decorating `package.json` and placing it in the dist/ folder correctly with references to the bundle files, these are not present in the symlinked `package.json` in the root of the designsystem project. 

We might have to opt for npm symlinking, but I am unsure of the consequences this has on lerna caching and publishing, so we will have to investigate that approach a bit more.

**Comment by RasmusKjeldgaard** [comment]
The core library is very likely to change in the near future, and we might not continue using stencil. 
Therefore, I think this should be closed, and we can think about introducing the changes in the above comment☝
