### ISSUE TITLE
[Housekeeping] Rename `master` branch to `stable`

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2026]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

To reflect our release management strategies the `master` branch should be renamed ➡️  `stable`.

When renaming the branch CI/CD stuff will break and must be updated.

- [ ] Rename branch
- [ ] Fix CI/CD

## Have you considered any alternatives?

Other names that are _not_ similar to `main`.

**Comment by MadsBuchmann** [comment]
More specifically i think we need to be aware of: 
1. [publish.yml](https://github.com/kirbydesign/designsystem/blob/main/.github/workflows/publish.yml)
   -  it is triggered from 'master' branch
   - it uses the `actions/checkout@v2` action which i think checks out the default branch. Which means it would release changes from `main` instead of `stable`. 
  
2. I think [cleaup-branch-deployment.yml](https://github.com/kirbydesign/designsystem/blob/main/.github/workflows/cleanup-branch-deployment.yml) is good to go 

3. [build.yml](https://github.com/kirbydesign/designsystem/blob/main/.github/workflows/build.yml) has several references to the `master` branch which will have to be updated to `stable`.
   - it also uses the `actions/checkout@v2` action. Same point as above. 

I might be wrong about `actions/checkout@v2` and how it works as actions runs per branch. But we just need to be wary of it.

**Comment by RasmusKjeldgaard** [comment]
For documentation purposes: 
Initially I thought renaming would be quite a mess, as we link to our files on the master branch in Github rather often throughout documentation and so on. But it turns out renaming a branch redirect all previous links to the new name: 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch. Only exception is raw file URLs, which I think is acceptable.
