### ISSUE TITLE
[BUG] Exception: ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by troelslenda** [kirbydesign/designsystem#2031]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
As part of reducing errors in general we discovered **Exception: ResizeObserver loop limit exceeded** in Azure App Insights. 
The exception is thrown when a page implements kirby-page with fit directive. The bug only occur in Chrome Webview. 

## Describe how to reproduce the bug
1. Execute any application that implements kirby-page with fit-directive in any way on the Android Emulator
2. navigate to the view/page
3. See the exception thrown in Logcat.

## Which Kirby version was used?
5.0.18 (The bug has been known for some time but was only now located as a bug within kirby-page)

## What was the expected behavior?
The bug has apparently no implications for the user.

## Please complete the following information:
- OS: Android
- Browser: Chrome Webview
- Browser version: 87, 94, 96, 97, 98 (according to Azure App Insights - probably more)

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
# Reproducing 
1. The error actually [occurs in standard Chrome browsers, not only webview](https://stackoverflow.com/questions/64238740/how-to-ignore-the-resizeobserver-loop-limit-exceeded-in-testcafe/64257593#64257593), but is muted by default. By registering an event listener, we can log it and actually reproduce this bug anywhere fit heading is used in e.g. the cookbook.
2. To verify this error happens on a mobile device too, I've create a minimal example. Checkout https://github.com/kirbydesign/kirby-kitchen-sink/commit/ef9deadb58762d77295063a456eb22c42a3ef278, and run it on an android device as specified in the readme to see the following in logcat in Android Studio:

```
E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"ResizeObserver loop limit exceeded","url":"http://localhost/tabs/tab1","line":0,"col":0,"errorObject":"null"}}
E/Capacitor/Console: File: http://localhost/tabs/tab1 - Line 0 - Msg: ResizeObserver loop limit exceeded
```

# Findings
1. Similarly to the above, in Chrome Webview when running on a device, the error seems to be thrown in the context of the window, not from the fitheading code itself, which is why [this approach](https://github.com/kirbydesign/designsystem/pull/2032/commits/3cb01b76a0b98ad0240c5726900e07fb4a907f29) does not seem to work. 
2. With [this change](https://github.com/kirbydesign/designsystem/commit/745e52d96442ba780ace17663ce015564942ec72) to the fit heading source code, the second (`E/Capacitor/Console`) error is muted, but unfortunately the error seems to be thrown in a different context from the window that we are interacting with in the fit heading directive.

**Comment by RasmusKjeldgaard** [comment]
After some more investigations, it seems that some of the original assumptions about not being able to debounce or timeout the header scaling to avoid the error are false. 

When I create the minimal repro in the kirby-kitchen-sink with [a simple page](https://github.com/kirbydesign/kirby-kitchen-sink/blob/ef9deadb58762d77295063a456eb22c42a3ef278/src/app/home/home.page.html), the error can be muted by introducing a timeout or delay before doing the calculations. 

It seems that simply using `setTimeout` with a timeout of 0 will push any resize observing to the next frame or cycle, and avoid this error altogether for all browsers.
