### ISSUE TITLE
[Enhancement] FAB Sheet: Use `kirby-button` instead of `<ion-fab-button>`

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2258]

**Comment by RasmusKjeldgaard** [comment]
`ion-fab-button` has some built in functionality so that a close/cross icon appears when the FAB sheet is opened, with a nice animation and all. It is also purpose-built for use together with the `ion-fab-list`. We would have to account for this ourselves if using the FAB version of our `kirby-button`. Therefore, I think it is better to leave it as is. 

There are still teams using the FAB version of our `kirby-button`, but without the fab sheet, so another solution might be to package the `ion-fab-button` into a `kirby-fab-button`, and deprecate the `isFloating` input on kirby-button. Then we could use the `kirby-fab-button` in both the standalone use-case and the FAB sheet, but that would be another issue.
