### ISSUE TITLE
[Enhancement] Layout and responsiveness

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#2322]
Som bruger af netbank (privat/erhverv)
Ønsker jeg, at visningen af indhold kan tilpasse sig min enhed
Så overblik, funktioner og indhold vises optimalt på både mobil, desktop og tablet.

**Comment by RasmusKjeldgaard** [comment]
# High level thoughts 
This epic is about enabling layout in applications that use Kirby. Layout is not enabled by any specific component in Kirby (e.g. we wont expand the Grid component), but we want to build the proper layout utilities for DRB. This is probably a combination of code-pens that showcase the layout principles in general and specific implementations in the DRB Business solution, still built by Team Kirby. 

Are there any general packages with grid utilities out there that we should use, either directly or as inspiration?

These specific solutions should be built with a generalised theming/layout package in mind, so they can later be extracted to a utility library or similar maintained by Kirby. 

At least two Kirby components are _(maybe, probably)_ subject to changes to be easier to layout in target applications:
 - Page 
 @RasmusKjeldgaard please elaborate
 - Kirby Router Outlet
 @RasmusKjeldgaard please elaborate

# To Do
- [ ] Understanding the Layout System
  - [ ] Get a presentation (Dennis & @henrikvoetmand)
  - [ ] Build resizable demo of core principles
  - [ ] Share with designers (workshop?) and refine
- [ ] Initial use of Layout system in application
   - [ ] Start implementing the first utilities for grid etc. on the first page (for you page or similar) in DRB Business

**Comment by thupi** [comment]
The result of this issue was mainly the following: 

- CSS based Grid
- ~~New CSS based layout~~

It was decided to cancel the CSS layout solution as this required a lot of knowledge about how a consuming project would be setup. E.g. some of the pages didn't play nicely with the CSS layout solution as they required the scrollview to be inside the content area in order to implement sticky headers and scroll based title animations.

Initially the CSS layout was made so that the body of the site would be the scrollview, we would then use position: fixed to place the fixed elements on the screen. Some existing solution also used display:grid for the layout purposes. As the proposed solution used flex

Based on the above it wasn't easy to create a generic solution without knowing the different ways the consuming projects expected layout to work. Not to mention that layout in generel isn't identical from application to application.

Based on all the above there weren't good enough knowledge to base a generic layout solution on. For that reason, we went with the CSS Grid alone in the first run.
