### ISSUE TITLE
[BUG] Card in List missing box-shadow

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2446]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug

In Relationsbanken on the _Investment Overview_ (Investering) page there is a list of Cards. Each Card has a box-shadow but the top side is cut off. This is most obvious when you hover one of the cards.

It happens when a `kirby-card` is inside an `ion-item-sliding` inside a `kirby-list-item`. This is because both `ion-item-sliding` and `kirby-list-item` declares `overflow: hidden` so the box-shadow on `kirby-card` is cut off by those containers.

## Describe how to reproduce the bug

1. Go to https://dev.relationsbank.bankdata.dk/experiment-kirby-v7-rc4/jyskebank/mock/drb/investment/overview (link may be dead when this issue is to be solved)
2. See that there is no top box-shadow on the cards

## Which Kirby version was used?

7.0.0-rc.4

## What was the expected behavior?

The box shadow should not be cut off.

## Add any screenshots

Currently looks like this:

https://user-images.githubusercontent.com/150451/187505585-26954306-9532-4b75-8dab-64f9f2fed1e9.mov

Should look like this:

https://user-images.githubusercontent.com/150451/187506426-b7e92d8f-44dd-4089-9172-1df2b1bacb52.mov

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by RasmusKjeldgaard** [comment]
Turns out this is an existing problem, and not related to v7. So also a problem on v6. 
As stated by @jkaltoft the team is putting a card inside their list item, which means the card shadow is cut off by the surrounding items. The DOM looks something like this in the end: 

```html
<kirby-list>
   <kirby-list-item>
       <ion-item-sliding>
           <kirby-card>
               /* The rest of kirby-item stuff goes here. */
           </kirby-card>
       </ion-item-sliding>
   </kirby-list-item>
</kirby-list>
```

As far as I am concerned, this is not the intended use of the list, as the list itself should provide the card-like look. You should not put a card inside the list for styling purposes like this - it already comes with drop shadow etc. for sections. 

One issue that needs to be solved here is how to create the intended separation between items - same as #1604.
Otherwise, the team will need to figure out a way to do this, possibly inserting a section between each item, with no title? Definitely a bit hacky, but maybe a workaround until we have found a better solution.
