### ISSUE TITLE
[Enhancement] Bold value in Kirby list

### ISSUE THREAD

**Issue by Ranjot-Kaur** [kirbydesign/designsystem#393]
**Is your enhancement request related to a problem? Please describe.**
We have a list(screenshot attached), which has different font styles which are not given by default. By using label in kirby-cell we can customise the font however, the width does not work properly in that case.

**Describe the solution you'd like**
Making the kirby-list-cell-line flexible to accept fonts and also the width of cell should adapt as per screen size

**Describe alternatives you've considered**
First approach - Using label inside kirby-cell which gives correct font but the width of the cell is not adaptive to screen size, and another approach- kirby-list-cell-line resolves width issue however, can't get the correct font.

**Additional context**
![image](https://user-images.githubusercontent.com/35022750/60486544-8c1ce780-9cbc-11e9-9cce-e8f9438bb482.png)

https://zpl.io/V0gNdqR

**Comment by labanos** [comment]
What fonts customizations are we talking about here? Does other teams have the same requirements to customize fonts?

**Comment by Ranjot-Kaur** [comment]
Hi @labanos , I am not really sure about other team requirements. But I had a discussion with Anders and Alexander and they suggested that i should raise a git request so that we can analyse how many people have this kind of requirement. To add more on the requirement, the fonts as shown in picture are not by default given by kirby list. Can we have the ability to give fonts as an attribute in kirby list?

**Comment by labanos** [comment]
@Ranjot-Kaur hmm im not sure i understand the issue 100%. There are multiple examples in zeplin where teams need the same "look and feel" in lists as you. And to me it sounds like the "wrong" place to "open" up for font customizations - as this shouldn't be needed - and controlled centrally.

which part of the image is the "problem"? and could you maybe link to a screen in zeplin and point out to me exactly which part is broken? Name? isin? currency? (i briefly touched base with Mads on this - and maybe the issue is missing alingment in zeplin?..)

**Comment by askarby** [comment]
I think the issue here is related to the columns, in a kirby-list item, being determined as a percentage of the full with. On a high-DPI device, 20% of the lists width may display a currency amount without an issue... but using the same layout, in a low-DPI device will truncate that amount.
