### ISSUE TITLE
[BUG] Toast inside of modal (Android)

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#477]
**Describe the bug**
If you open a toast inside of a modal, the toast will open behind the modal. 

**To Reproduce**
1. Open a modal
2. Open a toast from the modal

**Kirby version**
 - v.0.0.237

**Expected behavior**
The toast should always open on top so it's visible

**Native (please complete the following information):**
 Issue has been confirmed on Android however it maybe also affects iOS

**Comment by mmmtrifork** [comment]
This seems to be an issue with nativescript-feedback: https://github.com/EddyVerbruggen/nativescript-feedback/issues/11 

I have tested it on both iOS and Android and the problem only appears on Android

**Comment by adfdev** [comment]
> This seems to be an issue with nativescript-feedback: [EddyVerbruggen/nativescript-feedback#11](https://github.com/EddyVerbruggen/nativescript-feedback/issues/11)
> 
> I have tested it on both iOS and Android and the problem only appears on Android

yes only in android! Solution?

**Comment by sanved77** [comment]
Just some food for thought, I personally had it not working too, until I realized that I am opening up the modal in an **async await** making it run in a background thread instead of the UI thread, thus making it impossible for it draw on the UI thread. 
And when it tries to draw it on the background thread, the DecorView doesn't get the View to draw on and throws an exception which is being caught by the JS. 
You can try and set this to false under package.json to experiment - `discardUncaughtJsExceptions`

**Comment by mmmtrifork** [comment]
> > This seems to be an issue with nativescript-feedback: [EddyVerbruggen/nativescript-feedback#11](https://github.com/EddyVerbruggen/nativescript-feedback/issues/11)
> > I have tested it on both iOS and Android and the problem only appears on Android
> 
> yes only in android! Solution?

Unfortunately not.

**Comment by ckibsen** [comment]
RIP {N}
