### ISSUE TITLE
[BUG] Card - flat and cards with elevation is not the same size (width) on native

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#491]
**Describe the bug**
flat and cards with elevation is not the same size (width)

**To Reproduce**
1. Go to cards example
2. Measure width of card variations of elevation

**Kirby version**
 - v0.0.248

**Expected behavior**
Cards should have the same width, elevation or not

**Screenshots**
![image](https://user-images.githubusercontent.com/5496706/62608675-9015d800-b900-11e9-8919-053482861e48.png)

**Comment by bommariusser** [comment]
Not sure but it might be an issue on more then the cards, like lists and inputs and stuff that also can have an elevation :D

**Comment by mmmtrifork** [comment]
Related to #423 & #483:
- Unfortunately we cannot remove the margin completely, as that tampers with the elevations on {N}
- The margin required is the elevation number * 3/2, which is why cards with different elevation have currently have different margins
- In order to align the card widths, we need to use the same margin, which can be min. 6 (z-4 * 3/2), in order to preserve the elevation on highlighted cards. 

I will look into possibilities for aligning the widths, as that may require less than 3/2 of the elevation 

To answer your question @bommariusser I don't think it will affect other components, as these widths are something I introduced with #483

**Comment by bommariusser** [comment]
uhm that sounds very technical @mmmtrifork :) But it sounds like we're changing the shadow (visuals) to get the intended behavior? The solutions sound very similar, talking visuals. Maybe @jakobe can help?

**Comment by mmmtrifork** [comment]
The difference between the solutions is the vertical distance between the cards. On the first, they are dependent on the shadows. This implies that different card modes - disabled, normal & highlighted will have different heights. On the 2nd they are all the same, computed from the max-elevation (that is when the card is highlighted). This implies that with the 2nd solution, when the card is e.g. disabled, we will have unnecessary margins on top and bottom, but at least all card types will have the same height.

**Comment by bommariusser** [comment]
Not the biggest fan of margins on components @mmmtrifork 🤣
