### ISSUE TITLE
[BUG] List with header and sections - rounded corners (web)

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#507]
**Describe the bug**
If you have a list with list-header and sections the current styles wont make the first list item with rounded corners.

see screenshot

**Expected behavior**
The first item should have rounded corners even though it has a list header. Current styles of the list on web should just be modified. Right now it's actually excluded with :not(.has-header) which is wrong

**Screenshots**
![image](https://user-images.githubusercontent.com/5496706/62787105-45dd5400-bac4-11e9-8075-a5514c505623.png)

**Additional context**
This only affects web and is caused by the ionic change #102 where the styles and implementation of the list was changed

**Comment by bommariusser** [comment]
A list with header and sections looks like this:
![Skærmbillede 2019-08-13 kl  11 50 46](https://user-images.githubusercontent.com/49033002/62933193-ed5acf00-bdc1-11e9-9830-7dfc8606de89.png)

I'm not sure anyone uses it like this, nor if its the intended behavior of the list to be used like this? :) 

I can't find a use-case in our wires that does it like this, so maybe we put that back into the backlog until we get to a point where it will be needed.

@hafstad @labanos

**Comment by bdyken** [comment]
The missing rounded corners is showing on "posteringer"
![image](https://user-images.githubusercontent.com/49056452/64168721-6347d880-ce4c-11e9-9171-20e66eceb9b5.png)
The problem is in the styles for ion-item
![image](https://user-images.githubusercontent.com/49056452/64168798-a013cf80-ce4c-11e9-9475-7e2e88ba5372.png)
the style have e :not(.has-header)
![image](https://user-images.githubusercontent.com/49056452/64168838-ba4dad80-ce4c-11e9-9694-536fb9cb53ea.png)
