### ISSUE TITLE
[BUG] Back/Forward buttons are squeezed in {N}

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#563]
**Describe the bug**
Calendar seems to show the correct icons, but they are quite tiny/squeezed (maybe need an update of the font!?).

**To Reproduce**
1. Run Cookbook / Calendar in iOS simulator

**Kirby version**
 - [e.g. 0.0.262]

**Expected behavior**
Expect to see nice large icons like the ones on Web.

**Screenshots**
![Screenshot 2019-08-27 at 16 55 31](https://user-images.githubusercontent.com/832287/63782688-1021d300-c8ec-11e9-92f2-f2d0b83f4fa5.png)

**Native (please complete the following information):**
 - Device: iPhone Xs Max Simulator
 - OS: 12.4

**Additional context**

**Comment by mmmtrifork** [comment]
This comment is not a solution, just some remarks:
This issue is there because we are using "<" and ">" as plaintext, instead of actual icons. Unfortunately, the native WebView cannot directly import/utilize files around it, so instead we need to inject them somehow. A potential solution could be found by using https://www.npmjs.com/package/nativescript-webview-interface. A possible *temporary* (and not at all recommended) solution until the above-mentioned is resolved, would be to manually replace the plaintext "<" and ">" from within the buttons with the icon svgs. E.g.
```html
<button class="previous-button">
  <svg ...>...</svg>
</button>
```

**Comment by labanos** [comment]
{N} RIP
