### ISSUE TITLE
[Enhancement] Custom Icon support

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#585]
**Is your enhancement request related to a problem? Please describe.**
I cannot use custom icons in Empty State
**Describe the solution you'd like**
I would like to be able to use custom icons in Empty State

**Describe alternatives you've considered**
none

**Comment by trtbankdata** [comment]
Isn't this fixed with CustomIconName?
https://github.com/kirbydesign/designsystem/blob/722ed7acc808c502238ce1e5a27c10b239abd4de/src/kirby/components/empty-state/empty-state.component.ts#L10
https://github.com/kirbydesign/designsystem/blob/722ed7acc808c502238ce1e5a27c10b239abd4de/src/kirby/components/icon/icon.component.ts#L25

**Comment by labanos** [comment]
#425 solved this
