### ISSUE TITLE
[Enhancement] The user should not be able to close the modal by clicking outside the modal

### ISSUE THREAD

**Issue by Kristian2332** [kirbydesign/designsystem#621]
**At the moment it is possible to click outside the modal and then the modal will close down. However, it should only be possible to close the modal by clicking on the ‘X’ in the top right corner.**

**It is not possible to click outside the modal**

**Please go to the transfer flow or the buy/sell flow to view issue**

**Comment by bommariusser** [comment]
it should be a variabel i think @Kristian2332 but we actually talked about this today :) @labanos

**Comment by labanos** [comment]
We need to make sure this is actually how we want "modals" to work. Because if you want a non dismissable modal - use an Alert... If you want the user not to "break" a long flow... maybe warn the user when "dismissing"... or "save" the state and reopen in the same..  

Question is - do we have control over the "dismiss" action? Beucase if we do.. you could just ignore it?

Also how big is the problem if the modal takes up all of the screen?..
