### ISSUE TITLE
[Enhancement] Modal title should support long titles

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#843]
**Is your enhancement request related to a problem? Please describe.**
Right now our modals truncate on long titles, which makes some important text go away. 

**Describe the solution you'd like**
We would like the text to truncate only on scrolling down - So it will show the whole text when opening a modal.

![Skærmbillede 2019-12-19 kl  12 10 25](https://user-images.githubusercontent.com/49033002/71169612-a8f0ab80-2259-11ea-8ee8-240a02925b28.png)

**Describe alternatives you've considered**
We also thought of showing the whole title all the time, but prefer truncating on scrolling, like our page-template.

Also we have thought about scaling the title down to a p / 16 px before making the header bigger, down to the same size as the toolbar title.

<img width="888" alt="Skærmbillede 2021-03-08 kl  18 35 01" src="https://user-images.githubusercontent.com/49033002/110358746-029aec80-803d-11eb-873b-049635a383ee.png">

**Comment by flemcito** [comment]
Tech refinement: 
The modal header uses the ion-toolbar, which is quite limited with respect to what can be adjusted. Unfortunately the props that control height/overflow behaviour is not exposed. https://ionicframework.com/docs/api/toolbar.

- One way forward could be to replace the ion-toolbar with a custom component, but I am unsure of the implications this would have (ie. risk of breaking changes).
- Another way could be to create a variant of the modal with the collapsible header and make it an explicit choice to opt into that behaviour - so not to risk breaking existing implementations. 
- A third option could be to place the modal heading in the content area, and only use the toolbar to show a trunctacted heading when scrolled (like we do on pages)

**Comment by MadsBuchmann** [comment]
@jkaltoft Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Zenhub-602b70d809e4aa00141a1a93/issues/kirbydesign/designsystem/843?planning-poker)

**Comment by LVinther** [comment]
@alxzak as mentioned before we need to prioritize this issue - is it possible? :)

**Comment by bommariusser** [comment]
how does that work @MadsBuchmann ? :D can you demo that?

**Comment by MadsBuchmann** [comment]
@bommariusser got nothing to demo. I commented the above link as we stumbled upon it when discussing this issue yesterday. It's might just be a lever exposed by the ionic framework that we might use to implement the functionality, in a way exposed by the framework :D

**Comment by bommariusser** [comment]
alright @MadsBuchmann :) sounds great! The showcase is not so "not developer" friendly though so its hard to really understand what collapsible means :D sounds like something that gets smaller :P

**Comment by MadsBuchmann** [comment]
# Tech refinement 
I've spent some time looking into three different solutions for this: 
1. Using [ionics collapsible title functionality](https://ionicframework.com/docs/api/title#collapsible-large-titles) a PR with a POC has been uploaded in #2067. 
2. Simply making the title part of the content and never have it in the toolbar. 
3. Always having the title in `ion-toolbar` and truncating it on scroll 

I think we should go with no. 1. I've written down some pros & cons for this solution in #2067. The second will not be implemented due to UX considerations. When researching the third solution i stumbled into the problems mentioned by @flemcito by not being able to control overflow behaviour. 

There's still a couple of things to consider: 
- [ ] How do we make this so it becomes opt-in? 
- [ ] Is there a way to dynamically applying the solution? Such that if the title is too long for the modal it will automatically use the collapsible title functionality? 
- [ ]  What should the API for using it be?
- [ ] How to make this so it does not affect other types of modal than the default one.
