### ISSUE TITLE
[BUG]Input samsung device

### ISSUE THREAD

**Issue by laljyskebank** [kirbydesign/designsystem#910]
**Describe the bug**
On android devices, maxlength on input field is not working. It is possible to write more characters than specified.

**To Reproduce**

1. Go to 'Faste betalinger'
2. Click on 'FAB'
3. Click on 'Tilmeld Betalingsservice'
4. Click on 'Beskrivelse'
5. Enter more than 32 characters

![Screen Shot 2020-01-23 at 11 52 42](https://user-images.githubusercontent.com/35138247/72978532-eb685380-3dd6-11ea-9c8e-90f20ed361ce.png)

**Kirby version**
- v0.0.83

**Expected behavior**
Restrict characters to maxlength

**Comment by laljyskebank** [comment]
Link til PR, hvor der er noget historik

https://github.com/kirbydesign/designsystem/pull/883

**Comment by jakobe** [comment]
As Kirby doesn't have any tooling regarding validation, this is not to be handled by Kirby.
The bug is a general bug related to Samsung devices and html input + maxlength attribute.
The bug can be mitigated by validating the length on keyup and displaying an error message as the user types (see "Error" example on https://cookbook.kirby.design/home/showcase/form-field)
