### ISSUE TITLE
[Enhancement] Inline Footer functionality on kirby-page

### ISSUE THREAD

**Issue by sorenfruergaard** [kirbydesign/designsystem#918]
**Describe the solution you'd like**
We would like the possibility to have a footer which is always placed in the bottom. The footer should not be on top of the content like the ionic footer is and neither should it be fixed to the bottom of the window.

The footer should work in two ways.
1. If page content does not use the entire page, the footer should be placed in the bottom of the window.
2. If page content uses the entire page, the footer should be placed directly after the page contents. 

**Describe alternatives you've considered**
None

**Additional context**
1.
![Screenshot 2020-02-11 at 15 55 32](https://user-images.githubusercontent.com/2383744/74247970-2f1ff000-4ce7-11ea-838a-7e5456e0e0a0.png)
2.
<img width="796" alt="Screenshot 2020-02-11 at 15 59 10" src="https://user-images.githubusercontent.com/2383744/74248229-8b830f80-4ce7-11ea-8bb1-d040e72fc622.png">

**Comment by bommariusser** [comment]
@sorenfruergaard maybe we should talk about something that we could reuse in our modals, since we have the same "issue" in modals with not that much content, especially on bigger screens, where its awkward to find a position for the buttons you have in the very bottom of the page: It should be at the very bottom but the height on the devices are different.


Ill tried to mockup the issue and how it should work: A footer'ish thingy in the bottom of the "view" that is not dependent on the position u set it on the page.

![Skærmbillede 2020-02-13 kl  09 06 33](https://user-images.githubusercontent.com/49033002/74413715-3d355400-4e40-11ea-9d32-50489164c984.png)

**Comment by bommariusser** [comment]
We should also handle a way on how a sticky footer on a bigger screen is handled so that its not always lying on the very bottom but at the end of the content.

**Comment by jakobe** [comment]
Will be fixed by #958

**Comment by bommariusser** [comment]
should we close this @jakobe ?
